# Generated by Django 2.2.2 on 2019-07-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student1',
            table=None,
        ),
    ]
