# Generated by Django 2.2.2 on 2019-07-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20190717_1658'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student1',
            table='student2',
        ),
    ]
