# Generated by Django 2.2.2 on 2019-07-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20190717_1711'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student1',
            table=None,
        ),
    ]
